name: "Linters for Pull Request"

on:
  pull_request:
    branches:
      - "debank"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  lint:
    runs-on: [self-hosted, general]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private_key: ${{ secrets.RELEASE_MANAGER_APP_SECRET }}

      - name: Configure git for private modules
        run: |
          git config --global url."https://${{ steps.generate-token.outputs.token }}:x-oauth-basic@github.com/DeBankDeFi".insteadOf "https://github.com/DeBankDeFi"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true
