name: "Release new artifacts"

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  BUILT_BINARY_PATH: build/bin
  BUILT_BINARY_NAME: geth
  ARCHIVE_BUCKET: debank-build-artifacts
  ARCHIVE_FILE_PREFIX: downloads/ethereum
  AWS_REGION: ap-northeast-1

jobs:
  release-artifacts:
    runs-on: [self-hosted, general]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private_key: ${{ secrets.RELEASE_MANAGER_APP_SECRET }}

      - name: Make binaries
        run: |
          git config --global url."https://${{ steps.generate-token.outputs.token }}:x-oauth-basic@github.com/DeBankDeFi".insteadOf "https://github.com/DeBankDeFi"
          make

      - name: Set env
        run: |
          echo "ARCHIVE_FILE_NAME=eth-${GITHUB_REF#refs/*/}-linux-amd64" >> $GITHUB_ENV

      - name: Archive artifacts
        run: |
          mkdir $ARCHIVE_FILE_NAME
          cp $BUILT_BINARY_PATH/$BUILT_BINARY_NAME $ARCHIVE_FILE_NAME/$BUILT_BINARY_NAME
          sha256sum $ARCHIVE_FILE_NAME/$BUILT_BINARY_NAME --tag >> $ARCHIVE_FILE_NAME/sha256.checksum
          chmod u+x $ARCHIVE_FILE_NAME/$BUILT_BINARY_NAME
          $ARCHIVE_FILE_NAME/$BUILT_BINARY_NAME version
          tar cvfz $ARCHIVE_FILE_NAME.tar.gz $ARCHIVE_FILE_NAME
